# Generated by Django 3.0.8 on 2021-03-15 12:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0003_pet_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Enter color', max_length=30, unique=True)),
            ],
            options={
                'ordering': ['color'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(help_text='Enter gender', max_length=10, unique=True)),
            ],
            options={
                'ordering': ['gender'],
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default=0, help_text='Enter pet age'),
        ),
        migrations.AddField(
            model_name='pet',
            name='birth',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 20, 55, 45, 282789), help_text='Enter pet birth'),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter pet weigth', max_digits=4),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(default='', help_text='Enter description', max_length=300),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(default='', help_text='Enter pet name', max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet_shop.Type'),
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet_shop.Color'),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet_shop.Gender'),
        ),
    ]
