# Generated by Django 3.0.8 on 2021-03-15 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0004_auto_20210315_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.AlterField(
            model_name='pet',
            name='birth',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 20, 56, 26, 112215), help_text='Enter pet birth'),
        ),
    ]
