# Generated by Django 3.0.8 on 2021-03-16 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0006_auto_20210316_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birth',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 15, 50, 36, 173400), help_text='Enter pet birth'),
        ),
        migrations.AlterField(
            model_name='pet_vaccine_record',
            name='date',
            field=models.DateField(help_text='Enter Date'),
        ),
    ]
