# Generated by Django 3.0.8 on 2021-03-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0010_auto_20210316_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birth',
            field=models.DateField(help_text='Enter pet birth', null=True),
        ),
    ]
