# Generated by Django 3.0.8 on 2021-04-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0011_auto_20210316_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ['pk']},
        ),
        migrations.RenameField(
            model_name='record',
            old_name='adopt_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='username',
            new_name='user_id',
        ),
    ]
