# Generated by Django 3.0.8 on 2021-04-23 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0012_auto_20210414_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Enter Adopter name', max_length=30)),
                ('phone', models.CharField(default='', help_text='Enter Phone', max_length=30)),
                ('adopt_date', models.DateTimeField(auto_now_add=True)),
                ('pet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet_shop.Pet')),
            ],
            options={
                'ordering': ['name', '-adopt_date'],
            },
        ),
    ]
